// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:quotesy/models/quote.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(QuoteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(QuoteAdapter());
  }
}
